package dev.vanta.launcher;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * Build-time constants of the launcher. The values are generated by Gradle into
 * {@code dev/vanta/launcher/build-info.properties} from {@code gradle.properties}, so the pinned product
 * versions exist in exactly one place. Sensible fallbacks are used when the resource is missing (IDE runs).
 */
public final class LauncherVersion {

    /** Launcher version (SemVer). */
    public static final String VERSION;
    /** Minecraft version the launcher installs and launches. */
    public static final String MINECRAFT;
    /** Fabric Loader version. */
    public static final String FABRIC_LOADER;
    /** Fabric API version (Maven version string, e.g. {@code 0.141.6+1.21.11}). */
    public static final String FABRIC_API;
    /**
     * JavaFX platform classifier the jar was built for ({@code win}, {@code linux}, {@code mac-aarch64}, ...). The
     * fat jar bundles JavaFX natives for this platform only.
     */
    public static final String JAVAFX_PLATFORM;
    /** Java major version required by Minecraft 1.21.11. */
    public static final int JAVA_MAJOR = 21;
    /** Instance id used for the game directory and the {@code --version} argument. */
    public static final String INSTANCE_ID;
    /** HTTP user agent sent with every request. */
    public static final String USER_AGENT;

    static {
        final Properties props = new Properties();
        try (InputStream in = LauncherVersion.class.getResourceAsStream("/dev/vanta/launcher/build-info.properties")) {
            if (in != null) {
                props.load(in);
            }
        } catch (IOException ignored) {
            // fall through to defaults
        }
        VERSION = props.getProperty("launcher.version", "1.0.1");
        MINECRAFT = props.getProperty("minecraft.version", "1.21.11");
        FABRIC_LOADER = props.getProperty("fabric.loader.version", "0.19.5");
        FABRIC_API = props.getProperty("fabric.api.version", "0.141.6+1.21.11");
        JAVAFX_PLATFORM = props.getProperty("javafx.platform", "unknown");
        INSTANCE_ID = "vanta-" + MINECRAFT;
        USER_AGENT = "VANTA-Launcher/" + VERSION;
    }

    private LauncherVersion() {
    }

    /**
     * Human readable status line shown in the UI and the CLI.
     *
     * @return e.g. {@code Minecraft 1.21.11 · Fabric 0.19.5 · Java 21}
     */
    public static String statusLine() {
        return "Minecraft " + MINECRAFT + " · Fabric " + FABRIC_LOADER + " · Java " + JAVA_MAJOR;
    }
}
