package dev.vanta.core.waypoints;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import dev.vanta.core.bridge.Vec3d;
import java.util.Locale;
import java.util.Objects;
import java.util.Optional;

/**
 * One saved position. Waypoints are local data: they are written to {@code config/vanta/waypoints.json} and never
 * leave the computer.
 *
 * @param id        stable identifier generated by {@link WaypointStore} (never shown to the player)
 * @param name      display name, unique per world (case-insensitive), see {@link #sanitizeName(String)}
 * @param worldKey  world the waypoint belongs to, see {@link WorldKeys}
 * @param dimension dimension id such as {@code minecraft:overworld}
 * @param x         block-space X coordinate
 * @param y         block-space Y coordinate
 * @param z         block-space Z coordinate
 * @param color     ARGB marker colour
 * @param category  free-text category, see {@link WaypointCategories}
 * @param enabled   whether markers are drawn for it
 * @param createdAt creation time in epoch milliseconds
 */
public record Waypoint(String id, String name, String worldKey, String dimension, double x, double y, double z,
                       int color, String category, boolean enabled, long createdAt) {
    /** Longest name kept after {@link #sanitizeName(String)}. */
    public static final int MAX_NAME_LENGTH = 48;
    /** Name used when nothing printable remains after sanitising. */
    public static final String DEFAULT_NAME = "Waypoint";
    /** Dimension recorded when the game did not report one. */
    public static final String UNKNOWN_DIMENSION = "unknown";

    public Waypoint {
        Objects.requireNonNull(id, "id");
        Objects.requireNonNull(name, "name");
        Objects.requireNonNull(worldKey, "worldKey");
        Objects.requireNonNull(dimension, "dimension");
        Objects.requireNonNull(category, "category");
        if (id.isBlank()) {
            throw new IllegalArgumentException("Waypoint id must not be blank");
        }
        if (name.isBlank()) {
            throw new IllegalArgumentException("Waypoint name must not be blank");
        }
        if (worldKey.isBlank()) {
            throw new IllegalArgumentException("Waypoint worldKey must not be blank");
        }
        if (!Double.isFinite(x) || !Double.isFinite(y) || !Double.isFinite(z)) {
            throw new IllegalArgumentException("Waypoint coordinates must be finite: " + x + ", " + y + ", " + z);
        }
    }

    /** Position as a vector. */
    public Vec3d position() {
        return new Vec3d(x, y, z);
    }

    /** Euclidean distance in blocks from {@code from} to this waypoint. */
    public double distanceTo(Vec3d from) {
        return distanceTo(from.x(), from.y(), from.z());
    }

    /** Euclidean distance in blocks from the given coordinates to this waypoint. */
    public double distanceTo(double fromX, double fromY, double fromZ) {
        double dx = x - fromX;
        double dy = y - fromY;
        double dz = z - fromZ;
        return Math.sqrt(dx * dx + dy * dy + dz * dz);
    }

    /** True when the waypoint belongs to {@code worldKey}. */
    public boolean isIn(String worldKey) {
        return this.worldKey.equals(worldKey);
    }

    /** True when the waypoint belongs to {@code worldKey} and lies in {@code dimension}. */
    public boolean isIn(String worldKey, String dimension) {
        return isIn(worldKey) && this.dimension.equals(dimension);
    }

    /**
     * True when {@code other} is this waypoint's name, ignoring case. {@code other} goes through the same
     * {@link #sanitizeName(String)} as a stored name, so the text a caller passed to {@link WaypointStore#add}
     * (doubled spaces, control characters, more than {@value #MAX_NAME_LENGTH} characters) finds the waypoint again.
     */
    public boolean hasName(String other) {
        return other != null && name.equalsIgnoreCase(sanitizeName(other));
    }

    // ---- withers -----------------------------------------------------------------------------------------------

    public Waypoint withName(String newName) {
        return new Waypoint(id, newName, worldKey, dimension, x, y, z, color, category, enabled, createdAt);
    }

    public Waypoint withPosition(Vec3d position) {
        return withCoordinates(position.x(), position.y(), position.z());
    }

    public Waypoint withCoordinates(double newX, double newY, double newZ) {
        return new Waypoint(id, name, worldKey, dimension, newX, newY, newZ, color, category, enabled, createdAt);
    }

    public Waypoint withDimension(String newDimension) {
        return new Waypoint(id, name, worldKey, newDimension, x, y, z, color, category, enabled, createdAt);
    }

    public Waypoint withColor(int newColor) {
        return new Waypoint(id, name, worldKey, dimension, x, y, z, newColor, category, enabled, createdAt);
    }

    public Waypoint withCategory(String newCategory) {
        return new Waypoint(id, name, worldKey, dimension, x, y, z, color, newCategory, enabled, createdAt);
    }

    public Waypoint withEnabled(boolean newEnabled) {
        return new Waypoint(id, name, worldKey, dimension, x, y, z, color, category, newEnabled, createdAt);
    }

    // ---- JSON ----------------------------------------------------------------------------------------------------

    /** JSON form as stored in {@code waypoints.json} (the colour is written as {@code #AARRGGBB}). */
    public JsonObject toJson() {
        JsonObject json = new JsonObject();
        json.addProperty("id", id);
        json.addProperty("name", name);
        json.addProperty("worldKey", worldKey);
        json.addProperty("dimension", dimension);
        json.addProperty("x", x);
        json.addProperty("y", y);
        json.addProperty("z", z);
        json.addProperty("color", WaypointColors.toHex(color));
        json.addProperty("category", category);
        json.addProperty("enabled", enabled);
        json.addProperty("createdAt", createdAt);
        return json;
    }

    /**
     * Tolerant reverse of {@link #toJson()}: a missing id, name or world key or a non-finite coordinate makes the
     * entry invalid (empty); every other field falls back to a default. Unknown fields are ignored.
     */
    public static Optional<Waypoint> fromJson(JsonObject json) {
        Objects.requireNonNull(json, "json");
        Optional<String> id = string(json, "id");
        Optional<String> rawName = string(json, "name");
        Optional<String> worldKey = string(json, "worldKey");
        if (id.isEmpty() || id.get().isBlank() || rawName.isEmpty() || worldKey.isEmpty()
                || worldKey.get().isBlank()) {
            return Optional.empty();
        }
        String name = sanitizeName(rawName.get());
        Optional<Double> x = number(json, "x");
        Optional<Double> y = number(json, "y");
        Optional<Double> z = number(json, "z");
        if (x.isEmpty() || y.isEmpty() || z.isEmpty()) {
            return Optional.empty();
        }
        String dimension = string(json, "dimension").filter(d -> !d.isBlank()).orElse(UNKNOWN_DIMENSION);
        int color = WaypointColors.parse(json.get("color")).orElse(WaypointColors.DEFAULT);
        String category = WaypointCategories.sanitize(string(json, "category").orElse(null));
        boolean enabled = bool(json, "enabled", true);
        long createdAt = number(json, "createdAt").map(Double::longValue).orElse(0L);
        return Optional.of(new Waypoint(id.get().strip(), name, worldKey.get().strip(), dimension.strip(), x.get(),
                y.get(), z.get(), color, category, enabled, createdAt));
    }

    // ---- sanitising -----------------------------------------------------------------------------------------------

    /**
     * Turns free text into a display name: control characters removed, whitespace collapsed to single spaces,
     * trimmed, at most {@value #MAX_NAME_LENGTH} characters; {@link #DEFAULT_NAME} when nothing remains.
     */
    public static String sanitizeName(String raw) {
        String cleaned = collapse(raw, MAX_NAME_LENGTH);
        return cleaned.isEmpty() ? DEFAULT_NAME : cleaned;
    }

    /** Removes control characters, collapses whitespace, trims and truncates to {@code maxLength}. */
    static String collapse(String raw, int maxLength) {
        if (raw == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder(Math.min(raw.length(), maxLength));
        boolean pendingSpace = false;
        for (int i = 0; i < raw.length() && sb.length() < maxLength; i++) {
            char c = raw.charAt(i);
            if (Character.isISOControl(c) || Character.isWhitespace(c)) {
                pendingSpace = !sb.isEmpty();
                continue;
            }
            if (pendingSpace) {
                if (sb.length() + 1 >= maxLength) {
                    break;
                }
                sb.append(' ');
                pendingSpace = false;
            }
            sb.append(c);
        }
        return sb.toString();
    }

    /** Lower-case form used for case-insensitive name comparison. */
    static String fold(String name) {
        return name.strip().toLowerCase(Locale.ROOT);
    }

    private static Optional<String> string(JsonObject json, String key) {
        JsonElement e = json.get(key);
        if (e == null || !e.isJsonPrimitive() || !e.getAsJsonPrimitive().isString()) {
            return Optional.empty();
        }
        return Optional.of(e.getAsString());
    }

    private static Optional<Double> number(JsonObject json, String key) {
        JsonElement e = json.get(key);
        if (e == null || !e.isJsonPrimitive() || !e.getAsJsonPrimitive().isNumber()) {
            return Optional.empty();
        }
        try {
            double value = e.getAsDouble();
            return Double.isFinite(value) ? Optional.of(value) : Optional.empty();
        } catch (NumberFormatException ex) {
            return Optional.empty();
        }
    }

    private static boolean bool(JsonObject json, String key, boolean fallback) {
        JsonElement e = json.get(key);
        if (e == null || !e.isJsonPrimitive() || !e.getAsJsonPrimitive().isBoolean()) {
            return fallback;
        }
        return e.getAsBoolean();
    }
}
