#!/usr/bin/env bash
# Publishes small CI artifacts (game-test screenshots, built jars, installers) to the orphan branch `ci-artifacts`,
# one directory per label. Runs in GitHub Actions with GITHUB_TOKEN (contents: write). The branch is replaced with
# a single commit on every publish so it never grows; other labels already on the branch are kept. Several jobs may
# publish different labels at the same time, so the push uses --force-with-lease against the commit that was
# cloned and retries from a fresh clone when another job won the race. Nothing from this branch is used by builds.
#
#   scripts/ci/publish-screenshots.sh <source-dir> [label]
set -euo pipefail
SRC="${1:?source dir}"
LABEL="${2:-run}"
BRANCH="ci-artifacts"
if [ ! -d "$SRC" ] || [ -z "$(ls -A "$SRC" 2>/dev/null)" ]; then
  echo "No artifacts in $SRC; nothing to publish."
  exit 0
fi
REMOTE="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
for attempt in 1 2 3 4 5 6; do
  WORK=$(mktemp -d)
  BASE=""
  if git clone --quiet --depth 1 --branch "$BRANCH" "$REMOTE" "$WORK" 2>/dev/null; then
    BASE=$(git -C "$WORK" rev-parse HEAD)
    # Start a fresh single-commit history that carries the existing labels.
    git -C "$WORK" checkout --quiet --orphan "${BRANCH}-next"
  else
    rm -rf "$WORK"; mkdir -p "$WORK"
    git init --quiet "$WORK"
    git -C "$WORK" checkout --quiet --orphan "${BRANCH}-next"
    git -C "$WORK" remote add origin "$REMOTE"
  fi
  DEST="$WORK/$LABEL"
  rm -rf "$DEST"; mkdir -p "$DEST"
  cp -r "$SRC"/. "$DEST"/
  {
    echo "# CI artifacts"
    echo
    echo "Generated by GitHub Actions. Branch is rewritten on every run; do not depend on it."
    echo
    echo "- Last publish: label \`$LABEL\` from commit ${GITHUB_SHA:-unknown}"
    echo "- Run: ${GITHUB_SERVER_URL:-https://github.com}/${GITHUB_REPOSITORY:-}/actions/runs/${GITHUB_RUN_ID:-}"
    echo "- Updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo
    echo "## Labels"
    for d in "$WORK"/*/; do
      [ -d "$d" ] || continue
      echo "- \`$(basename "$d")\`: $(find "$d" -type f | wc -l) files"
    done
  } > "$WORK/README.md"
  git -C "$WORK" add -A
  git -C "$WORK" -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
    commit --quiet -m "ci: ${LABEL} for ${GITHUB_SHA:-unknown}" || { echo "Nothing changed."; exit 0; }
  if [ -n "$BASE" ]; then
    LEASE="--force-with-lease=refs/heads/${BRANCH}:${BASE}"
  else
    LEASE="--force-with-lease=refs/heads/${BRANCH}:"
  fi
  if git -C "$WORK" push --quiet "$LEASE" origin "HEAD:refs/heads/$BRANCH"; then
    echo "Published $(find "$DEST" -type f | wc -l) files to branch $BRANCH/$LABEL (attempt $attempt)"
    exit 0
  fi
  echo "Push rejected (another job published meanwhile); retrying from a fresh clone..."
  rm -rf "$WORK"
  sleep $((attempt * 3))
done
echo "::error::could not publish $LABEL to $BRANCH after 6 attempts"
exit 1
