#!/usr/bin/env bash
# Publishes game-test screenshots (and other small CI artifacts) to the orphan branch `ci-artifacts`.
# Runs in GitHub Actions with GITHUB_TOKEN (contents: write). Safe to re-run: the branch is replaced
# with a single commit each time so it never grows. Nothing from this branch is used by builds.
#
#   scripts/ci/publish-screenshots.sh <source-dir> [label]
set -euo pipefail
SRC="${1:?source dir}"
LABEL="${2:-run}"
BRANCH="ci-artifacts"
if [ ! -d "$SRC" ] || [ -z "$(ls -A "$SRC" 2>/dev/null)" ]; then
  echo "No artifacts in $SRC; nothing to publish."
  exit 0
fi
WORK=$(mktemp -d)
git clone --quiet --depth 1 --branch "$BRANCH" "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" "$WORK" 2>/dev/null || {
  git init --quiet "$WORK"
  git -C "$WORK" checkout --quiet --orphan "$BRANCH"
  git -C "$WORK" remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
}
DEST="$WORK/$LABEL"
rm -rf "$DEST"; mkdir -p "$DEST"
cp -r "$SRC"/. "$DEST"/
{
  echo "# CI artifacts"
  echo
  echo "Generated by GitHub Actions. Branch is rewritten on every run; do not depend on it."
  echo
  echo "- Source commit: ${GITHUB_SHA:-unknown}"
  echo "- Run: ${GITHUB_SERVER_URL:-https://github.com}/${GITHUB_REPOSITORY:-}/actions/runs/${GITHUB_RUN_ID:-}"
  echo "- Updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$WORK/README.md"
git -C "$WORK" add -A
git -C "$WORK" -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
  commit --quiet -m "ci: artifacts for ${GITHUB_SHA:-unknown} (${LABEL})" || { echo "Nothing changed."; exit 0; }
git -C "$WORK" push --quiet --force origin "HEAD:refs/heads/$BRANCH"
echo "Published $(find "$DEST" -type f | wc -l) files to branch $BRANCH/$LABEL"
