package dev.vanta.launcher.core.ai;

import dev.vanta.launcher.core.net.Downloader;
import dev.vanta.launcher.core.net.JdkHttpTransport;
import dev.vanta.launcher.core.paths.LauncherPaths;
import dev.vanta.launcher.core.util.Json;
import dev.vanta.launcher.core.util.OsInfo;
import dev.vanta.launcher.core.util.Sleeper;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.FileTime;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.TreeSet;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The shared {@code installed.json} contract ({@code shared/local-ai/fixtures/}): the launcher writes exactly the file the
 * client reads ({@code dev.vanta.core.ai.LocalAiInstalled}) and the release tooling writes. {@code installed.example.json}
 * was generated by core from {@code manifest.example.json} and the fixed inputs in the fixtures README; the launcher's
 * record built from the same inputs must serialise to the same JSON, and a directory laid out like the fixture must pass
 * the launcher's quick and full checks.
 */
class LocalAiInstalledTest {

    static final Path FIXTURES = Path.of("..", "shared", "local-ai", "fixtures");
    static final OsInfo LINUX = new OsInfo("linux", "x64", "6.8");
    static final String INSTALLED_AT = "2026-10-08T12:00:00Z";
    static final String VERIFIED_AT = "2026-10-08T12:05:00Z";
    static final long SERVER_MTIME = 1_791_460_800_000L;
    static final long MODEL_MTIME = 1_791_460_860_000L;
    static final byte[] SERVER_BYTES = "#!/bin/sh\necho fixture llama-server b11429\n".getBytes(StandardCharsets.US_ASCII);
    private static final Clock CLOCK = Clock.fixed(Instant.parse("2026-10-09T08:00:00Z"), ZoneOffset.UTC);

    @TempDir
    Path tmp;

    /** The 4096 fixture model bytes: byte i is (i * 7 + 3) &amp; 0xff, the first four bytes spell GGUF. */
    static byte[] modelBytes() {
        final byte[] bytes = new byte[4096];
        for (int i = 0; i < bytes.length; i++) {
            bytes[i] = (byte) ((i * 7 + 3) & 0xff);
        }
        bytes[0] = 'G';
        bytes[1] = 'G';
        bytes[2] = 'U';
        bytes[3] = 'F';
        return bytes;
    }

    static String fixtureText(final String name) throws IOException {
        return Files.readString(FIXTURES.resolve(name), StandardCharsets.UTF_8);
    }

    static JsonElement fixtureJson(final String name) throws IOException {
        return Json.tree(fixtureText(name));
    }

    static LocalAiManifest fixtureManifest() throws IOException {
        return LocalAiManifest.parse(fixtureText("manifest.example.json"));
    }

    static LocalAiInstalled.Files fixtureFiles() {
        return new LocalAiInstalled.Files(SERVER_BYTES.length, SERVER_MTIME, modelBytes().length, MODEL_MTIME);
    }

    /**
     * Every leaf of a JSON tree as {@code a.b.c}; the platform key below {@code runtime.platforms} is written as
     * {@code <platform>} so records for different platforms compare equal in shape.
     */
    static Set<String> keyPaths(final JsonElement element) {
        final Set<String> paths = new TreeSet<>();
        collect("", element, paths);
        return paths;
    }

    private static void collect(final String prefix, final JsonElement element, final Set<String> out) {
        if (!element.isJsonObject()) {
            out.add(prefix.isEmpty() ? "<root>" : prefix);
            return;
        }
        for (Map.Entry<String, JsonElement> e : element.getAsJsonObject().entrySet()) {
            final String key = "runtime.platforms".equals(prefix) ? "<platform>" : e.getKey();
            collect(prefix.isEmpty() ? key : prefix + "." + key, e.getValue(), out);
        }
    }

    @Test
    void theRecordBuiltFromTheFixedInputsSerialisesToTheSharedFixture() throws IOException {
        final LocalAiManifest manifest = fixtureManifest();
        final LocalAiInstalled record = LocalAiInstalled.of(manifest, "linux-x64", INSTALLED_AT, VERIFIED_AT, fixtureFiles());
        final JsonElement expected = fixtureJson("installed.example.json");
        assertEquals(expected, Json.tree(Json.toJson(record)), "the launcher writes exactly what core wrote");
        // Key order follows the record components, so the pretty printed text matches the fixture line by line as well.
        assertEquals(List.of("schemaVersion", "platform", "installedAt", "verifiedAt", "runtime", "model", "files"),
            new ArrayList<>(Json.tree(Json.toJson(record)).getAsJsonObject().keySet()));
        assertEquals(List.of("serverSize", "serverMtime", "modelSize", "modelMtime"),
            new ArrayList<>(Json.tree(Json.toJson(record)).getAsJsonObject().getAsJsonObject("files").keySet()));
        assertEquals(Set.of("linux-x64"), record.runtime().platforms().keySet(), "Runtime.only keeps one archive");
        assertTrue(manifest.runtime().only("amiga-m68k").platforms().isEmpty());
    }

    @Test
    void theFixtureReadsBackCompletely() throws IOException {
        final LocalAiInstalled installed = Json.parse(fixtureText("installed.example.json"), LocalAiInstalled.class);
        assertTrue(installed.isComplete());
        assertEquals(1, installed.schemaVersion());
        assertEquals("linux-x64", installed.platform());
        assertEquals(INSTALLED_AT, installed.installedAt());
        assertEquals(VERIFIED_AT, installed.verifiedAt());
        assertEquals("b11429", installed.runtime().tag());
        assertEquals("llama-b11429/llama-server", installed.runtimePlatform().orElseThrow().serverPath());
        assertEquals("runtime/b11429/linux-x64/llama-b11429/llama-server", installed.serverRelativePath());
        assertEquals("models/Qwen3-1.7B-Q8_0.gguf", installed.modelRelativePath());
        assertEquals(fixtureFiles(), installed.files());
        assertEquals("llama.cpp b11429, Qwen3-1.7B Q8_0", installed.describe());
        assertEquals(fixtureJson("installed.example.json"), Json.tree(Json.toJson(installed)), "read, write, same file");

        // Records without the sections the client needs are incomplete, not crashes.
        assertFalse(new LocalAiInstalled(1, "linux-x64", INSTALLED_AT, VERIFIED_AT, null, installed.model(), null).isComplete());
        assertFalse(new LocalAiInstalled(1, "macos-x64", INSTALLED_AT, VERIFIED_AT, installed.runtime(), installed.model(), null).isComplete(),
            "the runtime section holds no archive for that platform");
        assertEquals(new LocalAiInstalled.Files(0, 0, 0, 0), new LocalAiInstalled(1, null, null, null, null, null, null).files());
    }

    /** Lays the fixture out like an install: installed.json, the server at its serverPath, the model, with the recorded times. */
    static Path layOut(final Path localAiDir, final LocalAiInstalled installed) throws IOException {
        Files.createDirectories(localAiDir);
        Files.writeString(localAiDir.resolve(LocalAiService.INSTALLED_FILE), fixtureText("installed.example.json"), StandardCharsets.UTF_8);
        final Path server = LocalAiReport.resolve(localAiDir, installed.serverRelativePath());
        Files.createDirectories(server.getParent());
        Files.write(server, SERVER_BYTES);
        Files.setLastModifiedTime(server, FileTime.fromMillis(SERVER_MTIME));
        final Path model = LocalAiReport.resolve(localAiDir, installed.modelRelativePath());
        Files.createDirectories(model.getParent());
        Files.write(model, modelBytes());
        Files.setLastModifiedTime(model, FileTime.fromMillis(MODEL_MTIME));
        return localAiDir;
    }

    @Test
    void aDirectoryLaidOutLikeTheFixturePassesTheQuickAndFullChecks() throws IOException {
        final LauncherPaths paths = new LauncherPaths(tmp.resolve("data"));
        final LocalAiInstalled installed = Json.parse(fixtureText("installed.example.json"), LocalAiInstalled.class);
        layOut(paths.localAiDir(), installed);
        final LocalAiManifest manifest = fixtureManifest();
        try (Downloader downloader = new Downloader(new JdkHttpTransport("VANTA-Launcher/test"), Sleeper.NONE, 1, 1)) {
            final LocalAiService service = new LocalAiService(downloader, paths, LINUX, () -> manifest, CLOCK);
            final LocalAiReport quick = service.status();
            assertEquals(LocalAiState.INSTALLED, quick.state(), quick.problems().toString());
            assertFalse(quick.outdated());
            assertEquals("llama.cpp b11429, Qwen3-1.7B Q8_0", quick.describeVersions());
            assertEquals(Optional.of(paths.localAiDir().resolve("runtime").resolve("b11429").resolve("linux-x64").resolve("llama-b11429")
                .resolve("llama-server")), quick.serverExecutable());
            assertEquals(Optional.of(paths.localAiDir().resolve("models").resolve("Qwen3-1.7B-Q8_0.gguf")), quick.modelFile());
            assertEquals(fixtureJson("installed.example.json"), Json.tree(Files.readString(service.installedFile(), StandardCharsets.UTF_8)),
                "the quick check rewrites nothing");

            final LocalAiReport full = service.verify();
            assertEquals(LocalAiState.INSTALLED, full.state(), full.problems().toString());
            final LocalAiInstalled refreshed = full.installed().orElseThrow();
            assertEquals("2026-10-09T08:00:00Z", refreshed.verifiedAt(), "a full verification records when it ran");
            assertEquals(INSTALLED_AT, refreshed.installedAt());
            assertEquals(fixtureFiles(), refreshed.files(), "same sizes and times");
            assertEquals(keyPaths(fixtureJson("installed.example.json")),
                keyPaths(Json.tree(Files.readString(service.installedFile(), StandardCharsets.UTF_8))));

            // The same files with another manifest: not outdated by the quick check alone when the record still matches
            // itself, but the report says a different runtime is available.
            final String newer = fixtureText("manifest.example.json").replace("\"tag\": \"b11429\"", "\"tag\": \"b11500\"")
                .replace("b11429/llama-server", "b11500/llama-server").replace("llama-b11429-bin", "llama-b11500-bin")
                .replace("releases/tag/b11429", "releases/tag/b11500").replace("download/b11429/", "download/b11500/");
            final LocalAiService updated = new LocalAiService(downloader, paths, LINUX, () -> LocalAiManifest.parse(newer), CLOCK);
            final LocalAiReport outdated = updated.status();
            assertEquals(LocalAiState.INSTALLED, outdated.state(), outdated.problems().toString());
            assertTrue(outdated.outdated());

            // A complete record written for another platform is partial on this one; one whose runtime section does not
            // hold the archive of its own platform is incomplete.
            Files.writeString(service.installedFile(), fixtureText("installed.example.json").replace("\"platform\": \"linux-x64\"",
                "\"platform\": \"macos-x64\"").replace("\"linux-x64\": {", "\"macos-x64\": {"), StandardCharsets.UTF_8);
            final LocalAiReport other = service.status();
            assertEquals(LocalAiState.PARTIAL, other.state());
            assertTrue(other.problems().get(0).contains("was written for macos-x64, this system is linux-x64"), other.problems().toString());
            Files.writeString(service.installedFile(), fixtureText("installed.example.json").replace("\"platform\": \"linux-x64\"",
                "\"platform\": \"macos-x64\""), StandardCharsets.UTF_8);
            final LocalAiReport incomplete = service.status();
            assertEquals(LocalAiState.PARTIAL, incomplete.state());
            assertTrue(incomplete.problems().get(0).contains("installed.json is incomplete"), incomplete.problems().toString());
        }
    }

    @Test
    void theFixtureManifestHashesAreTheDocumentedBytes() throws IOException {
        final LocalAiManifest manifest = fixtureManifest();
        assertTrue(manifest.problems(false).isEmpty(), manifest.problems(false).toString());
        assertEquals(dev.vanta.launcher.core.net.Checksums.hex(modelBytes(), dev.vanta.launcher.core.net.HashAlgorithm.SHA256),
            manifest.model().sha256());
        assertEquals(modelBytes().length, manifest.model().size());
        for (Map.Entry<String, LocalAiManifest.PlatformFile> e : manifest.runtime().platforms().entrySet()) {
            final byte[] archive = ("VANTA Local AI fixture archive " + e.getValue().file() + "\n").getBytes(StandardCharsets.US_ASCII);
            assertEquals(archive.length, e.getValue().size(), e.getKey());
            assertEquals(dev.vanta.launcher.core.net.Checksums.hex(archive, dev.vanta.launcher.core.net.HashAlgorithm.SHA256),
                e.getValue().sha256(), e.getKey());
        }
    }

    @Test
    void resolveWalksForwardSlashSegments() {
        final Path dir = tmp.resolve("ai");
        assertEquals(dir.resolve("runtime").resolve("b1").resolve("linux-x64").resolve("bin").resolve("llama-server"),
            LocalAiReport.resolve(dir, "runtime/b1/linux-x64/bin/llama-server"));
        assertEquals(dir.resolve("models").resolve("m.gguf"), LocalAiReport.resolve(dir, "models//m.gguf"));
        assertEquals(dir, LocalAiReport.resolve(dir, ""));
        final JsonObject nested = Json.tree("{\"a\":{\"b\":1,\"c\":{\"d\":2}},\"e\":3}").getAsJsonObject();
        assertEquals(Set.of("a.b", "a.c.d", "e"), keyPaths(nested));
    }
}
